"""Small async client for xAI's OpenAI-compatible Chat Completions API."""

from typing import Any

import httpx

from app.config import settings


async def create_json_completion(
    *,
    messages: list[dict[str, str]],
    temperature: float,
    max_tokens: int,
) -> str:
    """Return JSON text generated by the configured Grok model."""
    payload: dict[str, Any] = {
        "model": settings.XAI_MODEL,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "response_format": {"type": "json_object"},
    }
    headers = {
        "Authorization": f"Bearer {settings.XAI_API_KEY}",
        "Content-Type": "application/json",
    }

    async with httpx.AsyncClient(timeout=120.0) as client:
        response = await client.post(
            f"{settings.XAI_BASE_URL.rstrip('/')}/chat/completions",
            headers=headers,
            json=payload,
        )
        response.raise_for_status()

    data = response.json()
    content = data["choices"][0]["message"]["content"]
    if not content:
        raise ValueError("Grok returned an empty response")
    return content
